name: run-tests-laravel-10

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        php: [8.2, 8.1, 8.0]
        laravel: [10.*, 9.*]
        stability: [prefer-lowest, prefer-stable]

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install dependencies for laravel 9
        run: |
          composer require "laravel/framework:9.*" "orchestra/testbench:7.*" "nesbot/carbon:^2.63" --no-interaction --no-update
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction
        if: matrix.laravel == '9.*' && matrix.php >= 8.0

      - name: Install dependencies for laravel 10
        run: |
          composer require "laravel/framework:10.*" "orchestra/testbench:8.*" "nesbot/carbon:^2.63" "nesbot/carbon:${{ matrix.carbon }}" --no-interaction --no-update
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction
        if: matrix.laravel == '10.*' && matrix.php >= 8.1

      - name: List Installed Dependencies
        run: composer show -D

      - name: Execute tests
        run: vendor/bin/pest
